# Generated by Django 3.0.8 on 2020-07-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='photo',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='blogimg'),
        ),
    ]
